services:
  - type: web
    name: spring-boot-app
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/examMutants.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production